## Puerto de Ejecuci贸n
server:
  port: 9093
  #servlet:
    #context-path: /ms-rent-location

## Configuraci贸n de la BD
spring:
  data:
    mongodb:
      database: bd_product
      host: localhost
      port: 27017
      
## Configuraci贸n de open api
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  packages-to-exclude:
    - com.bcp.bootcamp.controller

logging:
  level:
    root: INFO
    com.alea: DEBUG
    org.springframework.boot: INFO

## CORS ORIGIN
cors:
  mapping: "/**"
  allowed-origins: http://localhost:4200, http://localhost:80
  allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
  allowed-head: "*"
  
## Configuraci贸n del Reactive Feign clients
feign:
  bcp-client:
    name: bcp-client

eureka:
   instance:
      hostname: localhost
      port: 8761
   client:
        serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka