## Puerto de Ejecución
server:
  port: 9092
  #servlet:
    #context-path: /ms-rent-location

## Configuración de la BD
spring:
  data:
    mongodb:
      database: bd_client
      host: localhost
      port: 27017

## Configuración de open api
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  packages-to-exclude:
    - com.bcp.bootcamp.controller

logging:
  level:
    root: INFO
    com.alea: DEBUG
    org.springframework.boot: INFO
  file:
    name: logs/bcp-client.log
    path: ./logs

## CORS ORIGIN
cors:
  mapping: "/**"
  allowed-origins: http://localhost:4200, http://localhost:80
  allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
  allowed-head: "*"

eureka:
   instance:
      hostname: localhost
      port: 8761
   client:
        serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka